newerpost: "Newer Post"
olderpost: "Older Post"
read: Read
next: Next
previous: Prev
myweibo: Weibo
mygithub: GitHub
mystackoverflow: "Stack Overflow"
mygoogleplus: Google+
myfacebook: Facebook
mytwitter: Twitter
myemail: Mail
blog: Blog
visitblog: "Visit the blog"
