name: Build and Deploy
on:
  push:
    branches:
      - hexo-source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false

    - name: Install
      run: |
        yarn
        yarn build
        yarn gulp
        yarn cdn

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: public

    - name: build algolia
      run: |
        export HEXO_ALGOLIA_INDEXING_KEY=${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
        yarn algolia

    - name: init issue
      run: |
        export ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
        node comment.js